export const themeParks = [
    { id: "efteling", name: "Efteling" },
    { id: "toverland", name: "Toverland" },
    { id: "walibiholland", name: "Walibi Holland" },
    { id: "walibibelgium", name: "Walibi Belgium" },
    { id: "plopsaland", name: "Plopsa de panne" },
    { id: "bellewaerde", name: "Bellewaerde" },
    { id: "bobbejaanland", name: "Bobbejaanland" },
    { id: "phantasialand", name: "Phantasialand" },
    { id: "movieparkgermany", name: "Movie park Germany" },
    { id: "holidaypark", name: "Holiday Park" },
    { id: "heidepark", name: "Heide Park" },
    { id: "rulantica", name: "Rulantica" },
    { id: "europapark", name: "Europa Park" },
    { id: "parcasterix", name: "Parc Asterix" },
    { id: "disneylandpark", name: "Dinsey paris (park)" },
    { id: "parquewarnermadrid", name: "Parque Warner Madrid" },
  ];