export const themeParks = [
  { id: "efteling", name: "Efteling" },
  { id: "toverland", name: "Toverland" },
  { id: "walibiholland", name: "Walibi Holland" },
  { id: "walibibelgium", name: "Walibi Belgium" },
  { id: "walibirhonealpes", name: "Walibi Rhône-Alpes" },
  { id: "plopsaland", name: "Plopsa de panne" },
  { id: "bellewaerde", name: "Bellewaerde" },
  { id: "bobbejaanland", name: "Bobbejaanland" },
  { id: "phantasialand", name: "Phantasialand" },
  { id: "movieparkgermany", name: "Movie park Germany" },
  { id: "holidaypark", name: "Holiday Park" },
  { id: "heidepark", name: "Heide Park" },
  { id: "rulantica", name: "Rulantica" },
  { id: "europapark", name: "Europa Park" },
  { id: "parcasterix", name: "Parc Asterix" },
  { id: "disneylandparis", name: "Dinsey paris (park)" },
  { id: "parquewarnermadrid", name: "Parque Warner Madrid" },
  { id: "legolandbillund", name: "LEGOLAND Billund" },
  { id: "liseberg", name: "Liseberg" },
  { id: "altontowersresort", name: "Alton Towers" },
  { id: "chessingtonworldofadventuresresort", name: "Chessington world of adventures" },
  { id: "legolandwindsor", name: "Legoland Windsor" },
];