export const themeParks = [
  { id: "efteling", name: "Efteling", parkLink: "https://www.efteling.com/nl/tickets/parkeerticket", parkTicket: "https://www.efteling.com/nl/tickets" },
  { id: "toverland", name: "Toverland", parkLink: "https://tickets.toverland.com/nl/tickets", parkTicket: "https://tickets.toverland.com/nl/tickets" },
  { id: "walibiholland", name: "Walibi Holland", parkLink: "https://reservation.walibi.nl/addons/PARKING", parkTicket: "https://www.walibi.nl/nl/tickets" },
  { id: "walibibelgium", name: "Walibi Belgium",  parkTicket: "https://www.walibi.be/nl/tickets" },
  { id: "walibirhonealpes", name: "Walibi Rhône-Alpes",  parkTicket: "https://www.walibi.fr/nl/billets" },
  { id: "plopsaland", name: "Plopsa de panne", parkLink: "https://www.plopsa.com/nl/plopsaland-de-panne/tickets", parkTicket: "https://www.plopsa.com/nl/plopsaland-de-panne/tickets" },
  { id: "bellewaerde", name: "Bellewaerde", parkLink: "https://reservation.bellewaerde.be/addons/PARKING", parkTicket: "https://www.bellewaerde.be/nl/tickets" },
  { id: "bobbejaanland", name: "Bobbejaanland",  parkTicket: "https://www.bobbejaanland.be/nl/tickets" },
  { id: "phantasialand", name: "Phantasialand",  parkTicket: "https://www.phantasialand.de/nl/themapark/ticketprijzen-aanbiedingen/" },
  { id: "movieparkgermany", name: "Movie park Germany",  parkTicket: "https://www.movieparkgermany.de/en/tickets" },
  { id: "holidaypark", name: "Holiday Park",  parkTicket: "https://www.holidaypark.de/nl/tickets" },
  { id: "heidepark", name: "Heide Park", parkTicket: "https://www.heide-park.de/tickets" },
  { id: "rulantica", name: "Rulantica",  parkTicket: "https://tickets.rulantica.de" },
  { id: "europapark", name: "Europa Park",  parkTicket: "https://tickets.europapark.de" },
  { id: "parcasterix", name: "Parc Asterix",  parkTicket: "https://www.parcasterix.fr/billets" },
  { id: "disneylandparis", name: "Dinsey paris (park)",  parkTicket: "https://www.disneylandparis.com/nl-nl/tickets/" },
  { id: "parquewarnermadrid", name: "Parque Warner Madrid",  parkTicket: "https://www.parquewarner.com/entradas" },
  { id: "legolandbillund", name: "LEGOLAND Billund",  parkTicket: "https://www.legoland.dk/billetter/" },
  { id: "liseberg", name: "Liseberg",  parkTicket: "https://www.liseberg.se/biljetter/" },
  { id: "altontowersresort", name: "Alton Towers",  parkTicket: "https://www.altontowers.com/tickets-passes/" },
  { id: "chessingtonworldofadventuresresort", name: "Chessington world of adventures",  parkTicket: "https://www.chessington.com/tickets-passes/day-tickets/" },
  { id: "legolandwindsor", name: "Legoland Windsor", parkTicket: "https://www.legoland.co.uk/tickets-passes/" },
];